# Universal TTS System Configuration
system:
  name: "Universal TTS System"
  version: "1.0.0"
  log_level: INFO
  max_file_size_mb: 100
  concurrent_workers: 4

tts_engines:
  default: pyttsx3
  pyttsx3:
    rate: 150
    volume: 1.0

audio_output:
  bitrate: 192k
  channels: 2
  default_format: mp3
  sample_rate: 44100
  supported_formats:
  - mp3
  - wav
  - ogg
cache:
  cleanup_interval_hours: 24
  enabled: true
  max_age_days: 7
  max_size_mb: 100
file_processing:
  max_file_size_mb: 10
  supported_formats:
  - .txt
  - .docx
  - .pdf
  - .md
logging:
  file: logs/tts.log
  level: INFO
voice_profiles:
  default:
    engine: pyttsx3
    settings:
      rate: 150
      volume: 1.0
